getgrav/grav-plugin-form

form.php
Some small improvements for the validation process
=> Improve captcha validation

classes/form.php, form.php, templates/forms/default/form.html.twig
This PR adds full server-side validation support for forms using Grav built-in internals (`Validation` class!) via blueprints and cleans up the code a bit.
**EDIT:** ~~Please do not merge yet! I have some minor tweaks, I would like to add. In the meantime feel free to comment on the code.~~
Ok, ready to be merged! :grinning:
=> Feature: Server side validation

languages.yaml
+ languages sorted alphabetically
=> Croatian translation

templates/forms/field.html.twig
deals with https://github.com/getgrav/grav-plugin-login/issues/36
=> Add for attribute to labels

languages.yaml
:fr: updated + reordering other languages than en
=> :fr: updated + reordering other languages than en

languages.yaml
:fr: updated
Please **NOTE** that the key line 13 (and then for other languages) is: `DATA_SUMAMRY:` instead of: `DATA_SUMMARY:` ?
Thanks
=> :fr: updated + Typo?

languages.yaml
[IN PROGRESS] :fr: updated to line 93
=> :fr: updated

classes/form.php, form.php
Makes it possible to have forms on pages generated on demand (e.g. registration form)
Refs https://github.com/getgrav/grav-plugin-login/pull/97
=> Fix Forms 2.0 changes for registration form

templates/forms/fields/captcha/captcha.html.twig
=> Fixing typo in field key

CHANGELOG.md, form.php, templates/forms/fields/fieldset/fieldset.html.twig
Globally takes into account non-pre-processed forms:
* Registration Page
* Profile Page
* Comments
* Admin User Create Page
...
=> Refactor form-processing

languages.yaml
Second try :-) I'm sorry, but I'm still learning GitHub processes ...
=> Add Czech language

templates/forms/default/field.html.twig
Implemented the idea of adding custom attributes to fields brought up by @dimitrilongo in #173.
=> issue #173 add custom attribute to field

languages.yaml
Just a little contribute for my favourite CMS.
=> Adding some missing italian phrase in languages.yaml 

form.php
=> Improving honeypot validation check

templates/forms/default/form.html.twig
See #195 for more information.
=> Remove trailing slash from form action (#195)

classes/form.php, form.php, templates/form-messages.json.twig, templates/partials/form-messages.json.twig
This PR is to fix this issue #163 and #210
=> Fix AJAX response message and wrong status when form is submitted twice

form.php, templates/forms/default/data.txt.twig
=> Escape YAML to form save action to prevent parsing errors

templates/forms/fields/checkbox/checkbox.html.twig
Added markdown processing to checkbox label (if markdown is enabled).
This makes #227 fully functional for my requirements.
=> Added markdown processing to checkbox label (if markdown is enabled) #227

languages.yaml
added german translation strings for YES / NO
=> added german translation strings

classes/Form.php
The proposed changes allow for a better integration with other plugins, especially in the context of dynamically created routes and forms that rely on an empty page definition.
=> Better plugin support for uploaded files

languages.yaml
=> Update Russian translation

templates/forms/fields/captcha/captcha.html.twig
Site_key was not correctly set.
=> fix. capcha issue #334

languages.yaml
This pull request aims to complete and improve the accuracy of the Grav Form Plugin's Polish translation.
P.S. Thanks to whoever made the mistakes in `DROPZONE_FALLBACK_MESSAGE`, fixing which was to be the single and only change in this pull request... :upside_down_face:
=> Improve Polish translation

languages.yaml
- Fix typo in English for mime types errors;
- Add a few missing French strings.
=> Fix and additions in i18n strings:

templates/forms/default/field.html.twig
which are polluting html output
=> Remove extraneous leftovers

CHANGELOG.md
Hello,
Simple fix of markdown link in the changelog.
Regards,
Anael
=> Fix markdown link in changelog

templates/forms/fields/email/email.html.twig, templates/forms/fields/tel/tel.html.twig, templates/forms/fields/url/url.html.twig
I've also found it very useful to add maxlength to other textfields as well. If there are more where you think this could make sense, please let me know.
=> Add min and maxlength also to email, url and tel template

templates/forms/fields/section/section.html.twig
https://github.com/getgrav/grav-plugin-form/pull/459#issuecomment-738880137
I also **tested this**.
=> Fix admin access check

templates/forms/default/data.html.twig
This is required to display the email correct.
=> Fix translations for select field in data template

languages.yaml
=> Add Lithuanian translation

CHANGELOG.md
=> Fix changelog display error

README.md, composer.json
=> Change links from http to https

templates/forms/fields/select/select.html.twig
Added `attributes` attribute to field.
=> Attributes attribute.

classes/BasicCaptcha.php
Added surrounding spaces to minus-operator when `$first_num` is greater than or equal to `$second_num`
=> Matched formatting of minus-operator with other results
