templates/forms/fields/checkboxes/checkboxes.html.twig, templates/forms/fields/radio/radio.html.twig
At the moment each radio box gets its own unique name. This way, the radio boxes aren't grouped and toggle mechanism does not work.
In addition, the patch harmonizes ID naming among checkboxes and radio boxes.
=> Fix radio inputs

templates/forms/default/form.html.twig, templates/forms/field.html.twig, templates/forms/fields/textarea/textarea.html.twig
I added a few small additions to the form plugin which may be useful for others:
- Added support for the `size` attribute of input fields
- Added support of the `rows` and `cols` attribute of textfields
- Made the text field the default type so the the type field can be ommitted in the form declaration
- Added the option to omit the label declaration. The label then defaults to the field name with the first letter in upper case (eg field name `address` becomes label `Address`)
This makes form declarations more concise as `type: text` and most trivial labels can be omitted.
=> Support for cols,rows and size attribute, default type is text and label can be ommited

templates/forms/fields/checkboxes/checkboxes.html.twig
This PR enables to translate checkboxes label for different languages using eg.
```yaml
checkbox:
type: checkboxes
label: PLUGIN.CHECKBOXES_LABEL
default:
key: true
options:
key: PLUGIN.CHECKBOXES_KEY_LABEL
use: keys
```
=> Make checkboxes label translateable

classes/form.php
Currently it picks the settings in the wrong way, and even after fixing
it, it merges the config (adding multiple and destination as arrays, so
the code following will break as it assumes those are strings). The new
code replaces the default values with the array values set in the field.
=> Correctly merge the file field configuration

README.md
There was a typo in the readme. I have replaced forms/forms.yaml by form/form.yaml
=> Fix type in readme : replace forms/forms.yaml by form/form.yaml

form.php
Pages containing forms were failing. Changing the capitalisation for the file link fixed it.
=> fixed capitlisation on form class link

templates/forms/fields/captcha/captcha.html.twig
As the widget is explicitly rendered, onload callback function must be defined before the reCAPTCHA API loads.
To ensure there are no race conditions:
- order your scripts with the callback first, and then reCAPTCHA  
(Documented here: https://developers.google.com/recaptcha/docs/display)
Not sure if this is the case for everybody, it worked for me with a Bootstrap Theme.
=> Callback must be defined before reCAPTCHA loads

templates/forms/fields/checkbox/checkbox.html.twig
As the label is disabled to render before the input on type checkbox and instead add the custom label after, [this previous merged PR](https://github.com/getgrav/grav-plugin-form/commit/e000483a30895b4b1da1266fda7cdd5fc572cdda) will not add the attribute, till now. 
Also relates to earlier issue regarding best practise to achieve the attribute. 
Read [this link](https://github.com/getgrav/grav-plugin-form/issues/56)
Anyhow, the added code will improve ^^
=> Update to support attribute `for="id"` on label for checkbox

classes/form.php, form.php, templates/form.html.twig, templates/formdata.html.twig, templates/forms/default/data.html.twig, templates/forms/default/data.txt.twig, templates/forms/default/form.html.twig
This PR addresses the need to have some fields sent through the form, but not being part of the form data.
In particular the use case was the Captcha field, which should not be saved / visualized after being processed server-side.
The fields to be stored are now under the `data.*` scope. 
Adding `input@: false` to a field will make it being ignored in save / display actions.
Also, the PR adds the default page templates for form handling, causing less friction for users of themes that do not provide a form page template.
In the form definition, if you are adding custom Twig processing for form values, the location `form.value.*` is now `form.value.data.*`, e.g. :
```
email:
body: '{% include "forms/data.html.twig" %}'
from: '{{ form.value.email }}'
```
(sets the 'from' email value to the …
=> Add scope to form data

templates/forms/fields/spacer/spacer.html.twig
This PR allows text inside `spacer` to be translated according the current language settings by Grav or by the logged in use. It further adds the option to process markdown on the text, too.
=> Allow text translations in `spacer` form fields

templates/forms/default/form.html.twig
This wrapping div is in a perspective very pointless. As the child output is a wrapping div - with proper attributes. The un-attributed parent makes it not best for styling, and a form is never nice to style when it is clogged. 
And from the yaml perspective, the `outerclasses` is applied to the child wrapping, so all I can ask is why wrapping two times?
=> Remove the <div> wrapping with no attributes

templates/forms/fields/hidden/hidden.html.twig
Allow to process twig, for example to add a custom value
```
xxxxxx:
type: hidden
default: "random()"
evaluate: true
validate:
type: string
```
=> Add optional evaluate to the hidden field

templates/forms/default/field.html.twig, templates/forms/fields/checkboxes/checkboxes.html.twig
This PR is related to [#667](https://github.com/getgrav/grav-plugin-admin/pull/667), which adds a field description to forms and allows to show help hints for checkboxes items:
**Usage:**
```yaml
mycheckboxes:
type: checkboxes
help_options:
copyright: 'Here comes the help text for copyright checkbox'
location: 'Here comes the help text for location checkbox'
options:
copyright: Copyright
location: Location
```
=> Set hints for checkboxes options and allow field descriptions

form.php
Fixes #83.
Note: Uses a more verbose, but clearer (and less broken) if/else block instead of nested ternary operators.
=> Fixes Recaptcha secret throwing errors

templates/forms/fields/textarea/textarea.html.twig
When a user sets the `classes` attribute  for a `textarea` field, the Twig template duplicates the class attribute inside the textarea tag, resulting in a not valid HTML like this:
**Markdown source**
```markdown
- name: message
classes: form-control
type: textarea
```
**Final HTML**
```html
<div class="form-textarea-wrapper">
<textarea class="form-control" name="data[message]" class="form-control"></textarea>
</div>
```
=> Fixed duplicate textarea class attribute

classes/form.php
Really small change, but Form#getPagePathFromToken threw an error for me without it.
=> Fixed errant reference to Grav DI container in Form#getPagePathFromToken

templates/forms/default/form.html.twig
Sometimes when defining a form it may be useful to add classes around buttons (same as the fields).
Example:
```yaml
fields:
-
name: email
placeholder: 'Email'
type: email
classes: form-control
outerclasses: col-md-2
buttons:
-
type: submit
classes: btn btn-block
outerclasses: col-md-2
value: 'Submit'
```
=> Extend buttons to support 'outerclasses'

templates/forms/default/field.html.twig
Sometimes, the placeholder field is enough to understand the form hence the label is not necessary.
Setting `label` to` false` will disable the label block.
=> Added the ability to disable fields label

form.php
I have a requirement in my grav setup to do replacement within a redirect.
The use case is this: I am requiring users to complete a simple form before downloading a PDF. Upon completion, the redirect goes to the PDF, using a hidden field in the form I'm populating from the querystring.
=> Allow form item replacement in redirect location

templates/forms/fields/radio/radio.html.twig
The radio type wasn't properly getting a language value from a plugin so it was rendering as `PLUGIN.SQUIDGRID.SOMETHING` instead of the proper way. This fix proposes to put it in line with how the text is added in the select type which renders properly.
=> Bug fix for radio type form field

templates/forms/fields/captcha/captcha.html.twig
Fix for #139 triggers an alert for other forms in the same page which doesn't contains a captcha filed.
E.g: search form. This commit fix this issue by checking if the submitted form has the captcha field before the validation.
=> adds fix for #182

templates/forms/fields/select_optgroup/select_optgroup.html.twig
YAML layout of the new select_optgroup form field is:
```
header.newField:
type: select_optgroup
label: Test Optgroup Select Field
options:
- OptGroup1:
- Option1
- Option2
- OptGroup2:
- Option3
- Option4
```
=> Issue #165 Optgroup support. Added new field type select_optgroup

form.php, templates/forms/default/field.html.twig
I've used this simple hack successfully and it would certainly suit me to have it integrated.
The 'remember' processing instruction is useful in scenarios where a user is expected to repeatedly use a form and will want certain fields to be pre-populated with their values from last time. Obviously this is only appropriate in private user environments.
My use case was a medical referral form. Referring practitioners do not need to re-enter their own details each subsequent time they complete the form and can concentrate on patient details.
Here is the relevant form YAML:
```YAML
- name: practitioner-name
label: Practitioner name
type: text
hint: You will only need to complete this once per browser/device. It should be recalled subsequent occasions.
validate:
required: true
- name: …
```
=> Remembered fields feature

templates/forms/fields/textarea/textarea.html.twig
At the question of [@megalofauna](https://getgrav.slack.com/archives/C3Z7KN6MC/p1516882329000126) I gave this [answer](https://getgrav.slack.com/archives/C3Z7KN6MC/p1516885992000280).
In fact, the [@jgonyea](https://getgrav.slack.com/archives/C3Z7KN6MC/p1516886330000281) solution does not provide any changes to the code ... but the warning comes when you try to save the page.
I have made this PR if you think the solution is useful.
=> textarea, maxlength and minlength attributes

form.php
This pull request aim to add an auto form re-build process in the case of the internal form cache has been expired before the global pages grav cache.
Indeed if Grav hit the cache of the core Pages object, it will not trigger the `onPageProcessed` event (which is listen by the form plugin to build forms). So in this case, if the form cache expires before the Grav core Pages cache (yes it sometime happen, but I dont know why or when ^_^), then the form plugin (listing `onPageInitialized`) will get an empty form (because it was not built through the `onPageProcessed`) and an empty cache (because it was expired) and result to a completely broken form (no fields, no submit...).
I don't know if it's clear but this fix is in testing on my side in some live website and seems to correct the …
=> Added auto-rebuild form if internal cache fails

form.php
Some servers have `allow_url_fopen` disabled for security reasons. This causes CAPTCHA validation to fail and break the form submission because it relies on `file_get_contents()`.
This change adds a check for `allow_url_fopen` and a fallback to cURL.
=> cURL fallback for CAPTCHA validation

templates/forms/fields/honeypot/honeypot.html.twig
... and a hiding content technique:
The inline CSS `display:none` is useless because "turns off the
display of an element so that it has no effect on layout (the document
is rendered as though the element did not exist)." - Source
<https://developer.mozilla.org/en-US/docs/Web/CSS/display#display-box>
So the spambot can't fill it too.
The honeypot input must not be visible by human nor screen reader but
it should be focusable by a bot.
So I combined `visibility:hidden`, `aria-hidden="true"` and the content of the `.visuallyhidden` helper class of HTML5 Boilerplate.
=> Replace `display:none` by `visibility:hidden`

CHANGELOG.md, classes/Form.php, form.php
Fixed `Form::setFields()` causing validation to fail on added and removed fields
Added event `onFormPrepareValidation` to allow some pre-processing before form validation
Some code cleanup, PHP 5.5 updates
=> Fixed `Form::setFields()` causing validation to fail on added and removed fields

templates/forms/default/data.html.twig, templates/forms/default/data.txt.twig, templates/forms/fields/fieldset/fieldset.html.twig
This allows you to set an option in the `fieldset` (and potentially other nesting fields with minor changes), so that the data is prefixed by the id of the field.
Up to this point (and for backwards compatibility), nested fields like `fieldset`, were just flattened like so:
```
first_field: scooner
second_field: tugboat
name: my-slug
```
But with the fieldset field definition containing `nest_id: true`:
```
test-fieldset:
type: fieldset
legend: 'Test Fieldset'
nest_id: true
```
results in data structured:
```
test-fieldset.first_field: scooner
test-fieldset.second_field: tugboat
name: my-slug
```
=> Added support for nesting id’s - fieldset testcase

templates/forms/default/data.html.twig
Fixes change introduced in afa6eab in response to #121. Commit supported option value as index but broke rendering with option `use: keys`.
=> Fix HTML data template for checkboxes fields where 'use' property is "keys"

templates/forms/default/field.html.twig
Google Chrome complains: https://goo.gl/6KgkJg
> When wearing the autofill anchor mantle, the autocomplete attribute, if specified, must have a value that is an ordered set of space-separated tokens consisting of just autofill detail tokens (i.e. the "on" and "off" keywords are not allowed).
=> Typo fix, expanding autocomplete spec

templates/forms/fields/select/select.html.twig
Example:
`return ['AF' => 'Afghanistan', 'DZ' => ['value' => 'Algeria', 'selected' => 1], 'AS' => ['value' => 'American Samoa', 'disabled' => 1]];`
Supported attributes: `selected`, `disabled` and `label`
Note: For compatibility reason, the "`value`" subkey actually represents <option> text
while the top level array key represents actual option's "value" attribute.
=> PHP-defined <select> options can further specify attributes.

blueprints.yaml
This PR fixes the typo in the recaptcha version select (`blueprints.yaml`). Because of this, the code for repcatcha 2 invisible in `captcha.html.twig` was not executing.
=> Fix reCAPTCHA version option typo

package.json
The toolchain makes use of dependencies which are not part of `package.json`:
`npm install --save-dev gulp-webpack immutable uglifyjs-webpack-plugin`
See #291
=> missing npm build-time dependencies

templates/forms/default/field.html.twig
Currently when making a small field (usually for something like a number) but a description is needed this is the result:
This PR suggests removing the class from the description so it can be full width and result like this:
=> Visual upgrade to form field descriptions

templates/forms/default/field.html.twig
This PR is to fix a bug with escaping markdown label.
if we have for example:
```
date:
type: text
label: '**Choose a date**'
markdown: true
```
it will result in `<strong>Choose a date</strong>` when it should result in **Choose a date**
=> dont escape label markdown

classes/Form.php
Using `accept: 'image/svg+xml' to only allow SVG file to be uploaded should now work.
The `preg_match` was comparing `svgggg…xml` with `svg+xml`.
Check the [List of Media Types](https://www.iana.org/assignments/media-types/media-types.xhtml#image) for more potential issues.
=> Fix `accept` for SVG files in `file` uploaders:

form.php
When a form is requested by route, the routine extract the matching one then get its name, and then fetch form by name.
Not only is this sub-optimal but create a bug when two forms share the same name.
Eg: a **form is used as part of a modular page** and dynamically included in the template by its name. If another modular page exists, containing a page with an identical form slug, then this will fail.
- create two modular pages, each including a form, eg:
- `01.aaaa/01._formular/form.de_DE.md:    title: form-for-aaaa`
- `02.bbbb/01._formular/form.de_DE.md:    title: form-for-bbbb`
- You'll encounter that `01.aaaa` is using `02.bbbb`'s form or vice-and-versa **!!**
=> In case a route is requested and form exists: just return it immediately.
It may _radically change which forms get …
=> Prefer forms matching by route to avoid wrong result in case of name collision (was #309)

form.php
Some servers have `allow_url_fopen` disabled for security purposes. The ReCaptcha class relies on this by default, specifically through `file_get_contents()`, breaking validation for these servers.
This change allows the use of curl if it's available otherwise reverts to the default behavior.
=> Use curl for captcha validation if available

templates/forms/default/form.html.twig
Was part of #293, #294 and #336 here provided individually.
=> allow an empty form scope to be set from form parameters

templates/forms/layouts/field.html.twig
Show the `description` span even for an empty description because this field, even if empty at initial page load may be used and changed by javascript listeners.
This change allows author to user `description: ""` (empty string) to force its presence.
=> Show the `description` span even for an empty description

templates/forms/fields/tabs/tabs.html.twig
`count` is not a standard Twig filter. [length](https://twig.symfony.com/doc/2.x/filters/length.html) is
=> tabs: count is not a standard Twig filter. length is

templates/forms/default/data.txt.twig
Currently only done in html template.
Before:
```
PLUGIN_COMMENTS.NAME_LABEL: NicoHood
[...]
```
After:
```
Name: NicoHood
[...]
```
Useful when saving/logging form data to text file:
```yaml
save:
fileprefix: comments-
dateformat: Ymd-His-u
extension: txt
body: "{% include 'forms/data.txt.twig' %}"
```
=> Translate form labels also in text file

templates/forms/default/data.html.twig
Fixes https://github.com/getgrav/grav-plugin-form/issues/315
```yaml
my_field:
type: select
options:
option1: Option 1
option2: Option 2
option3: Option 3
label: "Test field"
multiple: true
validate:
required: true
type: array
```
=> Fix form data template when select field is set to multiple

templates/forms/layouts/field.html.twig
```
my_field:
type: checkboxes
options:
option1: Option 1
option2: Option 2
option3: Option 3
label: "Test field"
validate:
required: true
```
Before:
```
class="form-field form-grouphas-errors"
```
After:
```
class="form-field form-group has-errors"
```
This bug made the checkboxes render wrong, as some important classes were missing, due to the whitespace bug. Twig also removes other whitespaces outside the tag when using `{-`. I think the `trim` filter is always a better option. I did not check, if there are other places that also need a fix.
=> Fix has-errors for checkboxes and other fields

templates/forms/default/form.html.twig, templates/forms/layouts/form.html.twig
Form support for `data-*`or `config-data-*@` parameters to be used as `<form>` attributes 
See #173 and #293 and #294
=> Allow passing arbitrary form attributes

templates/forms/fields/section/section.html.twig
Please note:
* `h1` is still used in admin panel
* `h3` is the new default for frontend forms
* Use `title_level` attribute to customize the section title level
If the PR gets merged, I will add documentation for that feature as well.
=> Fix #453 section title level

templates/forms/default/form.html.twig
If `client_side_validation` is set to `false`, the `default` filter will always use the default of `true`.
=> Fix disabling of client_side_validation

classes/Form.php, form.php
You can define form process actions like this:
```
process:
captcha: true
ip: true
timestamp: true
```
But reversing this, so lets say set `captcha: false` will still try to validate the captcha.
I have added checks to these 3 process actions to check if they should be executed.
Maybe we should also consider to make this a general rule for all actions?
=> do not execute form action captcha, ip and timestamp if value is false

form.php
This PR makes forms try to find page by given route first instead of falling back to current page right away.
This fixes [missing forms issue described here](https://github.com/getgrav/grav/issues/3180), when form is included as a widget.
**NB:** This PR doesn't fix issue where `$this->forms` is empty and form still can't be found by name. This fixes only if form is searched by page route. Eg. `forms({'route':'my-page/route'})` while you're on another page
=> Fix missing forms issue after redirect

CHANGELOG.md, blueprints.yaml, composer.json, templates/forms/fields/toggle/toggle.html.twig
This change fixes #497 and simplifies the logic, but also requires Grav 1.7 in order to work (`|string` filter was made to work with boolean `false`).
It is possible to make this fix also in Grav 1.6 compatible way, but it gets a bit complicated.
=> Toggle fields do not save `false` if they are `toggleable` [#497]

templates/forms/fields/hidden/hidden.html.twig
It comes in handy if you want to do any value manipulation to it on AJAX submit. So to not search for element by `name` attribute, ID is very useful
=> Add `id` attribute to hidden field

templates/forms/fields/display/display.html.twig
This change will allow users to insert dynamically created contents inline on their forms. With this change, users can add something like this to their frontmatter on their fields within their pages:
```
content: '{{ page.content|raw }}'
evaluate: true
```
This PR doesn't include doc changes. :(
=> Updating the display field to allow dynamic input

templates/forms/fields/captcha/captcha.html.twig
Just `&theme={{ theme }}` in script URL does not work. Adding `data-theme="{{ theme }}"` to element itself does the trick.
Also [this is documented in Google reCaptcha docs](https://developers.google.com/recaptcha/docs/display#render_param)
=> Add reCaptcha theme to element via data attribute

templates/forms/fields/select/select.html.twig
This addresses the Issue#557 where iterable options wouldn't display/ save correctly.
=> Fixed select field where option is iterable

templates/forms/fields/checkboxes/checkboxes.html.twig
The 'checkboxes' field defines a set of checkboxes, but actually when the code references 'field.xxxx' it is referring to 'checkboxes', not to each individual checkbox, so with the current code, you cannot disable an individual checkbox in the set.
There is one scenario where this could be useful. A site developer might want to display some checkboxes inside a checkboxes field, disabled, just to inform the user, which can then be used in some twig template.
With these changes, I intend to improve the behavior of the checkboxes field so that you can choose which checkboxes are disabled.
- Added conditional disabling of checkboxes based on `disabled_options`.
- Added custom styles (opacity and cursor) for labels of disabled checkboxes.
- Moved the `for` loop inside the `<div>` element for …
=> Enhanced the `input` tag to include a disabled attribute

templates/forms/fields/tabs/tabs.html.twig
When tabs are hidden using the security@ feature, loop.index doesn't
match between tabs-nav and tabs-content
Fixes #524
=> Use tab field name instead of loop.index for navigation

templates/forms/fields/captcha/captcha.html.twig
When you put a form with recaptcha v3 in a modular deep in pages, Google return an error.
Changed the action path to a md5 which is shorter and respects Google's requirements
=> Correct action for deep modular page #571
